### ISSUE TITLE
Still crashing on canCaveSpiderSpawn after updating to 1.4.1

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [sf-inc/sihywtcamd#9]
Basically the same issue as described in https://github.com/sf-inc/sihywtcamd/issues/7, but on the mod version 1.4.1.

**MC** 1.17.1
**Fabric API** 0.37.1
**sihywtcamd** 1.4.1

Crash log: [crash-2021-07-28_01.42.49-server.txt](https://github.com/sf-inc/sihywtcamd/files/6889337/crash-2021-07-28_01.42.49-server.txt)

**Comment by charlyb01** [comment]
Hmm okay, I'll fix that. I guess it crashes less often than before but still crash if the position is equal to 0... But I don't know how do you have the issue because when I create a world with the datapack, it never tries to spawn them because the mojang dapatack overrides every mob spawn. Do you do anything more?

**Comment by Footage2-Amply-Pounce** [comment]
Nope, I just log into my existing world and after a very short period of time (varies from 1 to 10min) I get a crash. Didn't try with new worlds as I'm playing on a server. Could it be because I don't use the official datapack, but rather [this one](https://www.planetminecraft.com/data-pack/caves-amp-cliffs-expansion-pack-20w20a-compatible/)?

**Comment by charlyb01** [comment]
This datapack seems to act the same way. Let me give it some tries, I'll check this

**Comment by charlyb01** [comment]
Okay so I've been reading your crashlog and I just saw `mcmobs-dp-1-17-1.zip` datapack. Could you tell me what is it or link it?

**Comment by Footage2-Amply-Pounce** [comment]
Yep, it's [this one](https://www.planetminecraft.com/data-pack/minecon-minecraft-earth-mobs/). It adds unreleased mobs, such as warden and glutton, but they never spawn below 0.

**Comment by charlyb01** [comment]
Thanks. Can't find out how you got evrything working in your world 😅 I'll release a version with spawn (normally) fixed in this issue so that you can test it for me if it doesn't bother you.

**Comment by Footage2-Amply-Pounce** [comment]
Yeah, sure, I will test it.

**Comment by charlyb01** [comment]
[sihywtcamd-betatest.zip](https://github.com/sf-inc/sihywtcamd/files/6948970/sihywtcamd-betatest.zip)
This should work

**Comment by Footage2-Amply-Pounce** [comment]
Tested it for about 30min, just walking around, flying in creative and flying in spectator, especially around areas that previously caused a crash. So far seems to be fixed, I will let you know if the crash happens again. And I'll close the issue tomorrow if I still don't encounter a crash by then, unless you would like to close it now.

Thanks a lot!

**Comment by charlyb01** [comment]
Okay perfect, I will publish the fix on Curseforge soon then. You can still play with this version if you want, but I may add a change on the version I will release this afternoon. Have a nice day! =)
